# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 131473710a1d3fc0f361a927662a33b6522a86ced5548152f49c01a49a6f05dad356d668bfe4d7ce116745f6051202e1d8947866017a7d3ddc42a40fea85cb14

test:
  secret_key_base: dddaa8b0f816d3f78124f37ae8c44ab117edde68a595d63dece2e6851c911ed2a2eddaebf27897a0b989b95098cae0cf6c0db99880f2fb46d55c77610975e541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
